/* Generated by tools/generate-service-worker.js. Do not edit by hand. */
const CACHE_NAME = 'cognitive-game-1786553697252';
const ASSET_PATHS = [
  "assets/audio/background.mp3",
  "assets/food/乳鴿.webp",
  "assets/food/八爪魚.webp",
  "assets/food/冬瓜.webp",
  "assets/food/冬甩.webp",
  "assets/food/冬菇.webp",
  "assets/food/午餐肉.webp",
  "assets/food/南瓜.webp",
  "assets/food/叉燒.webp",
  "assets/food/叉燒包.webp",
  "assets/food/吞拿魚.webp",
  "assets/food/咕嚕肉.webp",
  "assets/food/咸水角.webp",
  "assets/food/四季豆.webp",
  "assets/food/墨魚.webp",
  "assets/food/奇異果.webp",
  "assets/food/姜.webp",
  "assets/food/娃娃菜.webp",
  "assets/food/小籠包.webp",
  "assets/food/山竹.webp",
  "assets/food/山竹牛肉球.webp",
  "assets/food/巧克力.webp",
  "assets/food/帶子.webp",
  "assets/food/春卷.webp",
  "assets/food/曲奇.webp",
  "assets/food/月餅.webp",
  "assets/food/木瓜.webp",
  "assets/food/木耳.webp",
  "assets/food/杏仁.webp",
  "assets/food/杏仁餅.webp",
  "assets/food/東坡肉.webp",
  "assets/food/枇杷.webp",
  "assets/food/柿子.webp",
  "assets/food/栗子.webp",
  "assets/food/核桃.webp",
  "assets/food/格仔餅.webp",
  "assets/food/桂花糕.webp",
  "assets/food/桃子.webp",
  "assets/food/桑椹.webp",
  "assets/food/梨.webp",
  "assets/food/椰子.webp",
  "assets/food/椰菜.webp",
  "assets/food/楊枝甘露.webp",
  "assets/food/楊桃.webp",
  "assets/food/榛子.webp",
  "assets/food/榴蓮.webp",
  "assets/food/橙子.webp",
  "assets/food/檸檬.webp",
  "assets/food/櫻桃.webp",
  "assets/food/比目魚.webp",
  "assets/food/洋蔥.webp",
  "assets/food/流沙包.webp",
  "assets/food/海參.webp",
  "assets/food/海膽.webp",
  "assets/food/涼瓜.webp",
  "assets/food/湯圓.webp",
  "assets/food/火龍果.webp",
  "assets/food/炒蜆.webp",
  "assets/food/烤鴨.webp",
  "assets/food/燒肉.webp",
  "assets/food/燒賣.webp",
  "assets/food/燕麥.webp",
  "assets/food/牛丸.webp",
  "assets/food/牛扒.webp",
  "assets/food/牛柏葉.webp",
  "assets/food/牛蒡.webp",
  "assets/food/玉米.webp",
  "assets/food/瓜子.webp",
  "assets/food/生蠔.webp",
  "assets/food/番石榴.webp",
  "assets/food/番茄.webp",
  "assets/food/番薯糖水.webp",
  "assets/food/白糖糕.webp",
  "assets/food/白菜.webp",
  "assets/food/白蘿蔔.webp",
  "assets/food/百香果.webp",
  "assets/food/石斑.webp",
  "assets/food/節瓜.webp",
  "assets/food/米飯.webp",
  "assets/food/粉粿.webp",
  "assets/food/糯米雞.webp",
  "assets/food/紅蘿蔔.webp",
  "assets/food/紅衫魚.webp",
  "assets/food/紅豆沙.webp",
  "assets/food/綠豆沙.webp",
  "assets/food/綠豆餅.webp",
  "assets/food/缽仔糕.webp",
  "assets/food/腰果.webp",
  "assets/food/腸仔.webp",
  "assets/food/腸粉.webp",
  "assets/food/臘腸.webp",
  "assets/food/芋頭.webp",
  "assets/food/芒果.webp",
  "assets/food/芝麻卷.webp",
  "assets/food/芝麻糊.webp",
  "assets/food/花椰菜.webp",
  "assets/food/花生.webp",
  "assets/food/芹菜.webp",
  "assets/food/茄子.webp",
  "assets/food/草莓.webp",
  "assets/food/荔枝.webp",
  "assets/food/菠蘿.webp",
  "assets/food/葡萄.webp",
  "assets/food/蒜頭.webp",
  "assets/food/蓮藕.webp",
  "assets/food/蔥.webp",
  "assets/food/藍莓.webp",
  "assets/food/蘋果.webp",
  "assets/food/蘑菇.webp",
  "assets/food/蘿蔔糕.webp",
  "assets/food/蛋卷.webp",
  "assets/food/蛋撻.webp",
  "assets/food/蛋散.webp",
  "assets/food/蛋糕.webp",
  "assets/food/蜆.webp",
  "assets/food/蝦.webp",
  "assets/food/蝦餃.webp",
  "assets/food/螃蟹.webp",
  "assets/food/西洋菜.webp",
  "assets/food/西瓜.webp",
  "assets/food/西蘭花.webp",
  "assets/food/豆腐花.webp",
  "assets/food/豉汁排骨.webp",
  "assets/food/象拔蚌.webp",
  "assets/food/豬肉.webp",
  "assets/food/豬腳.webp",
  "assets/food/金錢肚.webp",
  "assets/food/開心果.webp",
  "assets/food/雞扎.webp",
  "assets/food/雞翼.webp",
  "assets/food/雞蛋.webp",
  "assets/food/雞蛋仔.webp",
  "assets/food/雞髀.webp",
  "assets/food/雪糕.webp",
  "assets/food/青椒.webp",
  "assets/food/餃子.webp",
  "assets/food/餅乾.webp",
  "assets/food/香蕉.webp",
  "assets/food/香蕉糕.webp",
  "assets/food/馬拉糕.webp",
  "assets/food/馬鈴薯.webp",
  "assets/food/鮑魚.webp",
  "assets/food/鮭魚.webp",
  "assets/food/鱸魚.webp",
  "assets/food/鳳梨酥.webp",
  "assets/food/鳳爪.webp",
  "assets/food/麵條.webp",
  "assets/food/黃瓜.webp",
  "assets/food/黃立鯧.webp",
  "assets/food/黃花魚.webp",
  "assets/food/黑芝麻.webp",
  "assets/food/龍眼.webp",
  "assets/food/龍蝦.webp",
  "assets/gestures/left/four.webp",
  "assets/gestures/left/gun.webp",
  "assets/gestures/left/ok.webp",
  "assets/gestures/left/palmar_four.webp",
  "assets/gestures/left/palmar_gun.webp",
  "assets/gestures/left/palmar_ok.webp",
  "assets/gestures/left/palmar_paper.webp",
  "assets/gestures/left/palmar_rock.webp",
  "assets/gestures/left/palmar_scissors.webp",
  "assets/gestures/left/paper.webp",
  "assets/gestures/left/rock.webp",
  "assets/gestures/left/scissors.webp",
  "assets/gestures/left/thumbsdown.webp",
  "assets/gestures/left/thumbsup.webp",
  "assets/gestures/right/four.webp",
  "assets/gestures/right/gun.webp",
  "assets/gestures/right/ok.webp",
  "assets/gestures/right/palmar_four.webp",
  "assets/gestures/right/palmar_gun.webp",
  "assets/gestures/right/palmar_ok.webp",
  "assets/gestures/right/palmar_paper.webp",
  "assets/gestures/right/palmar_rock.webp",
  "assets/gestures/right/palmar_scissors.webp",
  "assets/gestures/right/paper.webp",
  "assets/gestures/right/rock.webp",
  "assets/gestures/right/scissors.webp",
  "assets/gestures/right/thumbsdown.webp",
  "assets/gestures/right/thumbsup.webp",
  "assets/icons/back.png",
  "assets/icons/menu.png",
  "css/app-chrome.css",
  "css/components.css",
  "css/food.css",
  "css/gng.css",
  "css/home.css",
  "css/layout.css",
  "css/nback.css",
  "css/reality.css",
  "css/responsive.css",
  "css/shopping.css",
  "css/unified.css",
  "css/variables.css",
  "icon-maskable.svg",
  "icon.svg",
  "icons/apple-touch-icon.png",
  "icons/icon-1024.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-1024.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "js/app-chrome.js",
  "js/food/audio.js",
  "js/food/data.js",
  "js/food/food.js",
  "js/food/gng.js",
  "js/food/main.js",
  "js/food/nback.js",
  "js/food/prefs.js",
  "js/food/shopping.js",
  "js/food/ui.js",
  "js/food/utils.js",
  "js/palm.js",
  "js/reality.js",
  "js/router.js",
  "manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      await cache.addAll(ASSET_PATHS);
    } catch (error) {
      console.warn('Precache incomplete:', error);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((key) => key !== CACHE_NAME)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, response.clone());
        return response;
      } catch (error) {
        const cached = await caches.match('index.html');
        if (cached) return cached;
        return new Response('Offline', {
          status: 503,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' }
        });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response.ok) {
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, response.clone());
      }
      return response;
    } catch (error) {
      return new Response('', { status: 408, statusText: 'Offline' });
    }
  })());
});
